Repository BuildForSDG/wasteCoin-Frontend, pull requests merged in 2020-06, with the labels that each got.

#34 [WALLET] Consume wallet api
  src/components/Footer/index.jsx
  src/components/RedeemCoinModal/index.jsx
  src/redux/index.js
  src/redux/reducers/constant.js
  src/redux/reducers/wallet.js
  src/views/Dashboard/index.jsx
  src/views/Wallet/index.jsx
  src/views/Wallet/wallet.css
Labels: enhancement

#37 Three New Features: Our Team page, FAQ and Private Policy
  public/index.html
  src/components/Footer/index.jsx
  src/images/faq.svg
  src/route.js
  src/views/FAQ/App.css
  src/views/FAQ/index.jsx
  src/views/Landing/App.css
  src/views/Landing/index.jsx
  src/views/OurTeam/App.css
  src/views/OurTeam/index.jsx
  src/views/PrivatePolicy/App.css
  src/views/PrivatePolicy/index.jsx
Labels: enhancement

#49 registration page and other bugs fixed
  README.md
  src/components/Header/index.jsx
  src/components/Layout/layout.css
  src/components/UserHeader/index.jsx
  src/components/UserSidebar/userSidebar.css
  src/images/Zubairu.jpg
  src/images/yayandi.jpg
  src/views/Landing/App.css
  src/views/OurTeam/index.jsx
  src/views/SignIn/index.jsx
Labels: bug

#54 Update readme to contain documentation of backend
  README.md
Labels: documentation

#57 [allocate-modal] Fix label
  src/components/AllocateCoinModal/index.jsx
Labels: bug

#58 Bugs- scroll
  src/components/Layout/layout.css
  src/views/Dashboard/dashboard.css
  src/views/Dashboard/index.jsx
  src/views/Wallet/index.jsx
  src/views/Wallet/wallet.css
Labels: bug

#60 app download log added to mobile landing page
  package.json
  src/images/aminu.jpg
  src/views/Dashboard/index.jsx
  src/views/Landing/index.jsx
  src/views/OurTeam/index.jsx
  yarn.lock
Labels: enhancement

#63 [Contact Form] Make contact form persist
  src/redux/reducers/constant.js
  src/redux/reducers/verify.js
  src/views/Landing/App.css
  src/views/Landing/index.jsx
  src/views/Wallet/index.jsx
Labels: enhancement

#64 Update Readme and remove scrollbar
  README.md
  src/components/Layout/layout.css
Labels: bug
